Allowed memory size of 1073741824 bytes exhausted
xaviered/php-WebHDFS pull request #16
Opened 2018-11-16 11:45 UTC by ehovel

add CURLOPT_WRITEFUNCTION  when i need to download big file

2018-11-16 11:47 UTC, ehovel commented
maybe we should add file lock

2019-04-15 21:38 UTC, xaviered requested changes
Please up the version https://github.com/xaviered/php-WebHDFS/blob/master/composer.json#L6 to `1.0.5`

2019-04-15 21:38 UTC, xaviered commented on src/org/apache/hadoop/tools/Curl.php
> +                fclose($fp);
Do we also want to do `fflush($fp)`?

2019-04-15 21:39 UTC, xaviered commented on src/org/apache/hadoop/tools/Curl.php
> +                fclose($fp);
Also, throw exceptions for `fopen` and 'fwrite`

2019-04-16 17:15 UTC, xaviered commented
Please rebase, as I just sent over a big change to use PSR-2 coding style standards

2019-04-30 03:22 UTC, ehovel commented
updated

2019-04-30 06:38 UTC, ehovel reviewed
updated version

2019-09-09 16:56 UTC, merged

2019-09-09 17:11 UTC, xaviered commented
@ehovel sorry for the very late follow up on this. I've added a couple of memory fixes too, and I've added your fix to a new version. You can get it at https://packagist.org/packages/simpleenergy/php-webhdfs#1.0.6